[package]
name = "ash-tui"
version.workspace = true
edition.workspace = true

[dependencies]
ash-core = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = { workspace = true }
pulldown-cmark = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
ansi-to-tui = "8.0.1"
