[package]
name = "ash-tools"
version.workspace = true
edition.workspace = true

[dependencies]
ash-core = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
tempfile = { workspace = true }
image = { workspace = true }
htmd = { workspace = true }
ignore = { workspace = true }
regex = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["process"] }

[dev-dependencies]
serde_json = { workspace = true }
