[package]
name = "ash-workflow"
version.workspace = true
edition.workspace = true

[dependencies]
ash-agent = { workspace = true }
ash-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
rquickjs = { workspace = true }
rquickjs-serde = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
tempfile = { workspace = true }
