[package]
name = "ash-workflow"
version.workspace = true
edition.workspace = true

[dependencies]
ash-agent = { workspace = true }
ash-collab = { workspace = true }
ash-core = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
futures = { workspace = true }
tempfile = { workspace = true }
